//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kur4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Виды.
    /// </summary>
    // *** Start programmer edit section *** (Виды CustomAttributes)

    // *** End programmer edit section *** (Виды CustomAttributes)
    public enum Виды
    {
        
        // *** Start programmer edit section *** (Виды.Поставщик CustomAttributes)

        // *** End programmer edit section *** (Виды.Поставщик CustomAttributes)
        [Caption("Поставщик")]
        Поставщик,
    }
}
