//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kur4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Питания.
    /// </summary>
    // *** Start programmer edit section *** (Питания CustomAttributes)

    // *** End programmer edit section *** (Питания CustomAttributes)
    public enum Питания
    {
        
        // *** Start programmer edit section *** (Питания.Завтрак CustomAttributes)

        // *** End programmer edit section *** (Питания.Завтрак CustomAttributes)
        [Caption("Завтрак")]
        Завтрак,
        
        // *** Start programmer edit section *** (Питания.Обед CustomAttributes)

        // *** End programmer edit section *** (Питания.Обед CustomAttributes)
        [Caption("Обед")]
        Обед,
        
        // *** Start programmer edit section *** (Питания.Ужин CustomAttributes)

        // *** End programmer edit section *** (Питания.Ужин CustomAttributes)
        [Caption("Ужин")]
        Ужин,
    }
}
