//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kur4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Питание.
    /// </summary>
    // *** Start programmer edit section *** (Питание CustomAttributes)

    // *** End programmer edit section *** (Питание CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПитаниеE", new string[] {
            "КодПитания as \'Код питания\'",
            "ВидПитания as \'Вид питания\'"})]
    [AssociatedDetailViewAttribute("ПитаниеE", "РегистрБлюд", "РегистрБлюдE", true, "", "Блюда", true, new string[] {
            ""})]
    [View("ПитаниеL", new string[] {
            "КодПитания as \'Код питания\'",
            "ВидПитания as \'Вид питания\'"})]
    public class Питание : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодПитания;
        
        private IIS.Kur4.Питания fВидПитания;
        
        private IIS.Kur4.DetailArrayOfРегистрБлюд fРегистрБлюд;
        
        // *** Start programmer edit section *** (Питание CustomMembers)

        // *** End programmer edit section *** (Питание CustomMembers)

        
        /// <summary>
        /// ВидПитания.
        /// </summary>
        // *** Start programmer edit section *** (Питание.ВидПитания CustomAttributes)

        // *** End programmer edit section *** (Питание.ВидПитания CustomAttributes)
        public virtual IIS.Kur4.Питания ВидПитания
        {
            get
            {
                // *** Start programmer edit section *** (Питание.ВидПитания Get start)

                // *** End programmer edit section *** (Питание.ВидПитания Get start)
                IIS.Kur4.Питания result = this.fВидПитания;
                // *** Start programmer edit section *** (Питание.ВидПитания Get end)

                // *** End programmer edit section *** (Питание.ВидПитания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Питание.ВидПитания Set start)

                // *** End programmer edit section *** (Питание.ВидПитания Set start)
                this.fВидПитания = value;
                // *** Start programmer edit section *** (Питание.ВидПитания Set end)

                // *** End programmer edit section *** (Питание.ВидПитания Set end)
            }
        }
        
        /// <summary>
        /// КодПитания.
        /// </summary>
        // *** Start programmer edit section *** (Питание.КодПитания CustomAttributes)

        // *** End programmer edit section *** (Питание.КодПитания CustomAttributes)
        public virtual int КодПитания
        {
            get
            {
                // *** Start programmer edit section *** (Питание.КодПитания Get start)

                // *** End programmer edit section *** (Питание.КодПитания Get start)
                int result = this.fКодПитания;
                // *** Start programmer edit section *** (Питание.КодПитания Get end)

                // *** End programmer edit section *** (Питание.КодПитания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Питание.КодПитания Set start)

                // *** End programmer edit section *** (Питание.КодПитания Set start)
                this.fКодПитания = value;
                // *** Start programmer edit section *** (Питание.КодПитания Set end)

                // *** End programmer edit section *** (Питание.КодПитания Set end)
            }
        }
        
        /// <summary>
        /// Питание.
        /// </summary>
        // *** Start programmer edit section *** (Питание.РегистрБлюд CustomAttributes)

        // *** End programmer edit section *** (Питание.РегистрБлюд CustomAttributes)
        public virtual IIS.Kur4.DetailArrayOfРегистрБлюд РегистрБлюд
        {
            get
            {
                // *** Start programmer edit section *** (Питание.РегистрБлюд Get start)

                // *** End programmer edit section *** (Питание.РегистрБлюд Get start)
                if ((this.fРегистрБлюд == null))
                {
                    this.fРегистрБлюд = new IIS.Kur4.DetailArrayOfРегистрБлюд(this);
                }
                IIS.Kur4.DetailArrayOfРегистрБлюд result = this.fРегистрБлюд;
                // *** Start programmer edit section *** (Питание.РегистрБлюд Get end)

                // *** End programmer edit section *** (Питание.РегистрБлюд Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Питание.РегистрБлюд Set start)

                // *** End programmer edit section *** (Питание.РегистрБлюд Set start)
                this.fРегистрБлюд = value;
                // *** Start programmer edit section *** (Питание.РегистрБлюд Set end)

                // *** End programmer edit section *** (Питание.РегистрБлюд Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПитаниеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПитаниеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПитаниеE", typeof(IIS.Kur4.Питание));
                }
            }
            
            /// <summary>
            /// "ПитаниеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПитаниеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПитаниеL", typeof(IIS.Kur4.Питание));
                }
            }
        }
    }
}
