




CREATE TABLE Контрагенты (
 primaryKey UUID NOT NULL,
 КодКонтиагента INT NULL,
 Наименование VARCHAR(255) NULL,
 Вид VARCHAR(9) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Питание (
 primaryKey UUID NOT NULL,
 КодПитания INT NULL,
 ВидПитания VARCHAR(7) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Должности (
 primaryKey UUID NOT NULL,
 КодДолжности INT NULL,
 Наименование VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Сотрудники (
 primaryKey UUID NOT NULL,
 КодСотрудника INT NULL,
 Фамилия VARCHAR(255) NULL,
 Имя VARCHAR(255) NULL,
 Отчество VARCHAR(255) NULL,
 Должности UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE РегистрБлюд (
 primaryKey UUID NOT NULL,
 КодБлюда INT NULL,
 Наименование VARCHAR(255) NULL,
 Количество INT NULL,
 Цена INT NULL,
 Питание UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE ДокументЗаказа (
 primaryKey UUID NOT NULL,
 КодДокумента INT NULL,
 ДатаДокумента TIMESTAMP(3) NULL,
 Сумма INT NULL,
 ЗаказСобран BOOLEAN NULL,
 ЗаказОтправ BOOLEAN NULL,
 ЗаказПолучен BOOLEAN NULL,
 Питание UUID NOT NULL,
 Контрагенты UUID NOT NULL,
 Сотрудники UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMNETLOCKDATA (
 LockKey VARCHAR(300) NOT NULL,
 UserName VARCHAR(300) NOT NULL,
 LockDate TIMESTAMP(3) NULL,
 PRIMARY KEY (LockKey));


CREATE TABLE STORMSETTINGS (
 primaryKey UUID NOT NULL,
 Module VARCHAR(1000) NULL,
 Name VARCHAR(255) NULL,
 Value TEXT NULL,
 "User" VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMAdvLimit (
 primaryKey UUID NOT NULL,
 "User" VARCHAR(255) NULL,
 Published BOOLEAN NULL,
 Module VARCHAR(255) NULL,
 Name VARCHAR(255) NULL,
 Value TEXT NULL,
 HotKeyData INT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERSETTING (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NOT NULL,
 DataObjectView VARCHAR(255) NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMWEBSEARCH (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NOT NULL,
 "Order" INT NOT NULL,
 PresentView VARCHAR(255) NOT NULL,
 DetailedView VARCHAR(255) NOT NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERDETAIL (
 primaryKey UUID NOT NULL,
 Caption VARCHAR(255) NOT NULL,
 DataObjectView VARCHAR(255) NOT NULL,
 ConnectMasterProp VARCHAR(255) NOT NULL,
 OwnerConnectProp VARCHAR(255) NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERLOOKUP (
 primaryKey UUID NOT NULL,
 DataObjectType VARCHAR(255) NOT NULL,
 Container VARCHAR(255) NULL,
 ContainerTag VARCHAR(255) NULL,
 FieldsToView VARCHAR(255) NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE UserSetting (
 primaryKey UUID NOT NULL,
 AppName VARCHAR(256) NULL,
 UserName VARCHAR(512) NULL,
 UserGuid UUID NULL,
 ModuleName VARCHAR(1024) NULL,
 ModuleGuid UUID NULL,
 SettName VARCHAR(256) NULL,
 SettGuid UUID NULL,
 SettLastAccessTime TIMESTAMP(3) NULL,
 StrVal VARCHAR(256) NULL,
 TxtVal TEXT NULL,
 IntVal INT NULL,
 BoolVal BOOLEAN NULL,
 GuidVal UUID NULL,
 DecimalVal DECIMAL(20,10) NULL,
 DateTimeVal TIMESTAMP(3) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE ApplicationLog (
 primaryKey UUID NOT NULL,
 Category VARCHAR(64) NULL,
 EventId INT NULL,
 Priority INT NULL,
 Severity VARCHAR(32) NULL,
 Title VARCHAR(256) NULL,
 Timestamp TIMESTAMP(3) NULL,
 MachineName VARCHAR(32) NULL,
 AppDomainName VARCHAR(512) NULL,
 ProcessId VARCHAR(256) NULL,
 ProcessName VARCHAR(512) NULL,
 ThreadName VARCHAR(512) NULL,
 Win32ThreadId VARCHAR(128) NULL,
 Message VARCHAR(2500) NULL,
 FormattedMessage TEXT NULL,
 PRIMARY KEY (primaryKey));



 ALTER TABLE Сотрудники ADD CONSTRAINT FKe5ecf5036053539899cbfb65cf7383292844b1ec FOREIGN KEY (Должности) REFERENCES Должности; 
CREATE INDEX Indexe5ecf5036053539899cbfb65cf7383292844b1ec on Сотрудники (Должности); 

 ALTER TABLE РегистрБлюд ADD CONSTRAINT FK8fa95838905dc771acd4cd4acbf7766da52e8b39 FOREIGN KEY (Питание) REFERENCES Питание; 
CREATE INDEX Index8fa95838905dc771acd4cd4acbf7766da52e8b39 on РегистрБлюд (Питание); 

 ALTER TABLE ДокументЗаказа ADD CONSTRAINT FKcc160b101f5d09ba4e8be62e1777675bb6b7501e FOREIGN KEY (Питание) REFERENCES Питание; 
CREATE INDEX Indexcc160b101f5d09ba4e8be62e1777675bb6b7501e on ДокументЗаказа (Питание); 

 ALTER TABLE ДокументЗаказа ADD CONSTRAINT FK90ad88b7f59dd7a61b68ee493c126e637d0b92a6 FOREIGN KEY (Контрагенты) REFERENCES Контрагенты; 
CREATE INDEX Index90ad88b7f59dd7a61b68ee493c126e637d0b92a6 on ДокументЗаказа (Контрагенты); 

 ALTER TABLE ДокументЗаказа ADD CONSTRAINT FKc403bec1c3ba7a31f7e22aac65be866c2a56dd90 FOREIGN KEY (Сотрудники) REFERENCES Сотрудники; 
CREATE INDEX Indexc403bec1c3ba7a31f7e22aac65be866c2a56dd90 on ДокументЗаказа (Сотрудники); 

 ALTER TABLE STORMWEBSEARCH ADD CONSTRAINT FKc4378e39870eb056aec84088683297a01d2a6200 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERDETAIL ADD CONSTRAINT FK921d16269835017e2a0d0e29ad6fb175454a70d0 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERLOOKUP ADD CONSTRAINT FKce38ef0db3f01a53acaa49fed8853fb941ad47ba FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

